/*
 * generated by Xtext 2.14.0
 */
package pnpl_variability.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPNPL_variabilityScopeProvider extends DelegatingScopeProvider {
}
