/**
 * generated by Xtext 2.15.0
 */
package pnpl_variability.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import pnpl_variability.services.PNPL_variabilityGrammarAccess;
import variability.Expression;
import variability.PresenceCondition;
import variability.UnaryExpression;
import variability.Variability;

@SuppressWarnings("all")
public class PNPL_variabilityFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private PNPL_variabilityGrammarAccess _pNPL_variabilityGrammarAccess;
  
  protected void _format(final Variability variability, @Extension final IFormattableDocument document) {
    EList<PresenceCondition> _presencecondition = variability.getPresencecondition();
    for (final PresenceCondition presenceCondition : _presencecondition) {
      document.<PresenceCondition>format(presenceCondition);
    }
  }
  
  protected void _format(final UnaryExpression unaryExpression, @Extension final IFormattableDocument document) {
    document.<Expression>format(unaryExpression.getRight());
  }
  
  public void format(final Object unaryExpression, final IFormattableDocument document) {
    if (unaryExpression instanceof XtextResource) {
      _format((XtextResource)unaryExpression, document);
      return;
    } else if (unaryExpression instanceof UnaryExpression) {
      _format((UnaryExpression)unaryExpression, document);
      return;
    } else if (unaryExpression instanceof Variability) {
      _format((Variability)unaryExpression, document);
      return;
    } else if (unaryExpression instanceof EObject) {
      _format((EObject)unaryExpression, document);
      return;
    } else if (unaryExpression == null) {
      _format((Void)null, document);
      return;
    } else if (unaryExpression != null) {
      _format(unaryExpression, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(unaryExpression, document).toString());
    }
  }
}
