/**
 * generated by Xtext 2.15.0
 */
package pnpl_variability;

import pnpl_variability.AbstractPNPL_variabilityRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PNPL_variabilityRuntimeModule extends AbstractPNPL_variabilityRuntimeModule {
}
