/**
 * generated by Xtext 2.15.0
 */
package pnpl_variability;

import pnpl_variability.PNPL_variabilityStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PNPL_variabilityStandaloneSetup extends PNPL_variabilityStandaloneSetupGenerated {
  public static void doSetup() {
    new PNPL_variabilityStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
