/*
 * generated by Xtext 2.15.0
 */
package pnpl_variability

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PNPL_variabilityRuntimeModule extends AbstractPNPL_variabilityRuntimeModule {
}
