/**
 * generated by Xtext 2.15.0
 */
package pnpl_variability.scoping;

import pnpl_variability.scoping.AbstractPNPL_variabilityScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class PNPL_variabilityScopeProvider extends AbstractPNPL_variabilityScopeProvider {
}
